// <auto-generated />
using System;
using CarDirectory.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarDirectory.Migrations
{
    [DbContext(typeof(AutomobileContext))]
    partial class AutomobileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarDirectory.Models.Automobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Create")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegisterSign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfIssue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegisterSign")
                        .IsUnique();

                    b.ToTable("Automobile");
                });
#pragma warning restore 612, 618
        }
    }
}
